### ISSUE TITLE
installation woes

### ISSUE THREAD

**Issue by rainwala** [hCoV-2019/pangolin#17]
Hi,
I'm trying to install on ubuntu 16.06.6 LTS, python 3.6.10

I ran the command 
`python3 setup.py install`

and got the following error when I tried riunning pangolin (after activating the environment):
`Traceback (most recent call last):
  File "/usr/local/bin/pangolin", line 9, in <module>
    load_entry_point('pangolin==0.1.0', 'console_scripts', 'pangolin')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/pangolin-0.1.0-py3.5.egg/pangolin/command.py", line 45
    print(f"The query file is {query}")
                                     ^
SyntaxError: invalid syntax`
Any ideas what could be going wrong?
Thanks.

**Comment by aineniamh** [comment]
Hi, 
I'm unable to replicate that error on my system, but it does look like you're using a different python version to install than you think as `py3.5.egg` and `python3.5` are listed in the error. 
If you double check you've activated the environment (`conda activate pangolin`), double check which python is running (`python --version`) and then try `python setup.py install` again? Let me know if that helps if not we can look further.

**Comment by rainwala** [comment]
Thanks, it works now. I think me trying "python3 install" rather than "python install" caused the error. Longing for the time when there is only one main branch of python that people can use...
